#ifndef _TextLib_CodeSolver_h_
#define _TextLib_CodeSolver_h_


BEGIN_TEXTLIB_NAMESPACE


class CodeSolver : public SolverBase {
	
public:
	enum {
		PHASE_GET_PLATFORMS,
		PHASE_GET_OPERATING_SYSTEMS,
		PHASE_GET_SW_LANGUAGES,
		PHASE_GET_SW_PARADIGMS,
		PHASE_GET_IDE,
		PHASE_GET_LIBRARIES,
		PHASE_GET_PROJECT_TYPES,
		PHASE_GET_BUILD_TOOLS,
		PHASE_GET_TESTING_FRAMEWORKS,
		PHASE_GET_DATABASE,
		PHASE_GET_USER_INTERFACE,
		PHASE_GET_SECURITY_FRAMEWORKS,
		PHASE_GET_DATA_FORMATS,
		PHASE_GET_ALGORITHMS,
		PHASE_GET_DATA_PROCESSING,
		PHASE_GET_DEPLOYMENT_ENVS,
		PHASE_GET_INTEGRATION_APIS,
		PHASE_GET_COLLABORATION_TOOLS,
		PHASE_GET_PROJECT_MANAGEMENTS,
		
		PHASE_GET_MARKET_TARGETS,
		PHASE_GET_MARKET_TRENDS,
		PHASE_GET_GENRES,
		PHASE_GET_USER_NEEDS,
		PHASE_GET_PRODUCTS,
		PHASE_GET_USER_FEEDBACKS,
		PHASE_GET_MARKETING_STRATEGIES,
		PHASE_GET_COLLABORATORS,
		PHASE_GET_REQUIREMENTS,
		PHASE_GET_PRICING,
		
		PHASE_COUNT
	};
	
	
	VectorMap<int, Index<int>> tmp_map;
	
public:
	typedef CodeSolver CLASSNAME;
	CodeSolver();
	
	int GetPhaseCount() const override;
	void DoPhase() override;
	
	static CodeSolver& Get(int appmode);
	
};


END_TEXTLIB_NAMESPACE


#endif
